spring.application.name=CleanCode

spring.datasource.url=jdbc:mysql://localhost:3306/clean_code_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true